Quiz_Learn/Quiz/src/java/model/Attempt.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import java.sql.Timestamp;

/**
 *
 * @author khiem
 */
public class Attempt {
    private int id;
    private Account account;
    private int quizId;
    private int Mark;
    private double grade;
    private int attempt;
    private Timestamp start;
    private Timestamp end;
    private String time;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Account getAccount() {
        return account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public int getQuizId() {
        return quizId;
    }

    public void setQuizId(int quizId) {
        this.quizId = quizId;
    }

    public int getMark() {
        return Mark;
    }

    public void setMark(int Mark) {
        this.Mark = Mark;
    }

    public int getAttempt() {
        return attempt;
    }

    public void setAttempt(int attempt) {
        this.attempt = attempt;
    }

    public Timestamp getStart() {
        return start;
    }

    public void setStart(Timestamp start) {
        this.start = start;
    }

    public Timestamp getEnd() {
        return end;
    }

    public void setEnd(Timestamp end) {
        this.end = end;
    }

    
    public Attempt() {
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public double getGrade() {
        return grade;
    }

    public void setGrade(double grade) {
        this.grade = grade;
    }

    public Attempt(int id, Account account, int quizId, int Mark, int attempt, Timestamp start, Timestamp end, String time) {
        this.id = id;
        this.account = account;
        this.quizId = quizId;
        this.Mark = Mark;
        this.attempt = attempt;
        this.start = start;
        this.end = end;
        this.time = time;
    }

    @Override
    public String toString() {
        return "Attempt{" + "id=" + id + ", account=" + account + ", quizId=" + quizId + ", Mark=" + Mark + ", grade=" + grade + ", attempt=" + attempt + ", start=" + start + ", end=" + end + ", time=" + time + '}';
    }

    
    
}

Quiz_Learn/Quiz/src/java/controller/HomeServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller;

import dal.PostDAO;
import dal.SubjectDAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.Cookie;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.util.ArrayList;
import model.Post;
import model.Subject;

/**
 *
 * @author khiem
 */
@WebServlet(name = "HomeServlet", urlPatterns = {"/subhome"})
public class HomeServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try ( PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet HomeServlet</title>");
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet HomeServlet at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
//        PrintWriter out = response.getWriter();
//        SubjectDAO d=new SubjectDAO();
//        ArrayList <Subject> a=(ArrayList <Subject>) d.getTopSubject();
//        for(Subject s:a){
//            out.println(s.toString());
//        }
//        PostDAO p=new PostDAO();
//        ArrayList <Post> c=(ArrayList <Post>) p.getTopPost();
//        for(Post s:c){
//            out.println(s.toString());
//        }
        
        request.getRequestDispatcher("Home.jsp").forward(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        doGet(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

Quiz_Learn/Quiz/src/java/controller/SliderController.java
package controller;

import java.io.IOException;
import java.util.List;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import model.Slider;
import dal.SliderDAO;

@WebServlet(name = "SliderController", urlPatterns = {"/slider"})
public class SliderController extends HttpServlet {

    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        SliderDAO sliderDAO = new SliderDAO(); 
        String raw_page = request.getParameter("page");
        int currentPage = 0;
        String sliderIdParam = request.getParameter("sliderId");
        double totalSlider = sliderDAO.getTotalSlider();
             
    if (sliderIdParam != null && !sliderIdParam.isEmpty()) {
        int sliderId = Integer.parseInt(sliderIdParam);
        SliderDAO dao = new SliderDAO();
        Slider slider = dao.getSliderById(sliderId);
        request.setAttribute("slider", slider);
        request.getRequestDispatcher("crudSlider.jsp").forward(request, response);
    }
            

            // Redirect or forward to the appropriate editing page with the sliderId
            // For example:
            // request.getRequestDispatcher("/edit-slider.jsp?id=" + sliderId).forward(request, response);
       
        if(raw_page == null){
            currentPage = 1;
        }else {
            currentPage = Integer.parseInt(raw_page);
        }
        int pageNum = (int) Math.ceil(totalSlider / 5); // chia trang
        int offset = (currentPage - 1) * 5; // vi tri ban ghi bat dau
        int fetch = 5; // so luong
        List<Slider> sliders = sliderDAO.getSliderPagination(offset, fetch);
        request.setAttribute("totalSlider", totalSlider);
        request.setAttribute("sliders", sliders);
        request.setAttribute("pageNum", pageNum);
        request.setAttribute("currentPage", currentPage);
        request.getRequestDispatcher("crudSlider.jsp").forward(request, response);
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
//        
//        String action = request.getParameter("action");
//        System.out.println("Actiojn "+ action);
//        if (action != null) {
//            if (action.equals("add")) {
//                
//                // Xử lý thêm Slider
//               
//            } else if (action.equals("edit")) {
//                // Xử lý sửa Slider
//                System.out.println("Go to editt");
//                int id = Integer.parseInt(request.getParameter("id"));
//                String title = request.getParameter("title");
//                String content = request.getParameter("content");
//                String notes = request.getParameter("notes");
//                String status = request.getParameter("status");
//                
//                Slider slider = new Slider();
//                slider.setSliderId(id);
//                slider.setTitle(title);
//                slider.setContent(content);
//                slider.setNotes(notes);
//                slider.setStatus(true);
//                
//                SliderDAO sliderDAO = new SliderDAO();
//                sliderDAO.updateSlider(slider);
//                
//                // Sau khi sửa xong, chuyển hướng về trang danh sách Slider
//                response.sendRedirect(request.getContextPath() + "/slider?action=list");
//            } else if (action.equals("delete")) {
//                // Xử lý xóa Slider
//                int id = Integer.parseInt(request.getParameter("id"));
//                
//                SliderDAO sliderDAO = new SliderDAO();
//                sliderDAO.deleteSlider(id);
//                
//                // Sau khi xóa xong, chuyển hướng về trang danh sách Slider
//                response.sendRedirect(request.getContextPath() + "/slider?action=list");
//            }
//        }
    }

    @Override
    public String getServletInfo() {
        return "Slider Controller";
    }
}

Quiz_Learn/Quiz/src/java/controller/SliderDetailController.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller;

import dal.SliderDAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import model.Slider;

/**
 *
 * @author ADMIN
 */
@WebServlet(name = "SliderDetailController", urlPatterns = {"/slider-details"})
public class SliderDetailController extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try ( PrintWriter out = response.getWriter()) {
          
            SliderDAO dao = new SliderDAO();
            int id = Integer.parseInt(request.getParameter("id"));
            Slider s = dao.getSliderById(id);
            request.setAttribute("slider", s);
            request.getRequestDispatcher("SliderDetail.jsp").forward(request, response);
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

Quiz_Learn/Quiz/src/java/controller/SliderListController.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller;

import dal.SliderDAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.util.List;
import model.Slider;

/**
 *
 * @author ADMIN
 */
@WebServlet(name = "SliderListController", urlPatterns = {"/slider-list"})
public class SliderListController extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try ( PrintWriter out = response.getWriter()) {
          SliderDAO dao = new SliderDAO();
          List<Slider> sliders = dao.getSliders();
          request.setAttribute("slider", sliders);
            request.getRequestDispatcher("SliderList.jsp").forward(request, response);
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

Quiz_Learn/Quiz/web/QuizAttempt.jsp
<%-- 
    Document   : chapterManagement
    Created on : Sep 10, 2023, 1:46:27 PM
    Author     : khiem
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c"  uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>${sessionScope.quiz.title}</title>
        <link rel="icon" href="images/Quikk.png" type="image/png">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <style>
            html * {

                font-family: 'Montserrat', sans-serif;

            }
            body {
                color: #566787;
                background: #f5f5f5;
/*                font-family: 'Varela Round', sans-serif;
                font-size: 13px;*/
            }
            .table-responsive {
                margin: 30px 0;
            }
            .table-wrapper {
                min-width: 1000px;
                background: #fff;
                padding: 20px 25px;
                border-radius: 3px;
                box-shadow: 0 1px 1px rgba(0,0,0,.05);
            }
            .table-title {
                padding-bottom: 15px;
                background: #299be4;
                color: #fff;
                padding: 16px 30px;
                margin: -20px -25px 10px;
                border-radius: 3px 3px 0 0;
            }
            .table-title h2 {
                margin: 5px 0 0;
                font-size: 24px;
            }
            .table-title .btn {
                color: #566787;
                float: right;
                font-size: 13px;
                background: #fff;
                border: none;
                min-width: 50px;
                border-radius: 2px;
                border: none;
                outline: none !important;
                margin-left: 10px;
            }
            .table-title .btn:hover, .table-title .btn:focus {
                color: #566787;
                background: #f2f2f2;
            }
            .table-title .btn i {
                float: left;
                font-size: 21px;
                margin-right: 5px;
            }
            .table-title .btn span {
                float: left;
                margin-top: 2px;
            }
            table.table tr th, table.table tr td {
                border-color: #e9e9e9;
                padding: 12px 15px;
                vertical-align: middle;
            }
            table.table tr th:first-child {
                width: 60px;
            }
            table.table tr th:last-child {
                width: 100px;
            }
            table.table-striped tbody tr:nth-of-type(odd) {
                background-color: #fcfcfc;
            }
            table.table-striped.table-hover tbody tr:hover {
                background: #f5f5f5;
            }
            table.table th i {
                font-size: 13px;
                margin: 0 5px;
                cursor: pointer;
            }
            table.table td:last-child i {
                opacity: 0.9;
                font-size: 22px;
                margin: 0 5px;
            }
            table.table td a {
                font-weight: bold;
                color: #566787;
                display: inline-block;
                text-decoration: none;
            }
            table.table td a:hover {
                color: #2196F3;
            }
            table.table td a.settings {
                color: #2196F3;
            }
            table.table td a.delete {
                color: #F44336;
            }
            table.table td i {
                font-size: 19px;
            }
            table.table .avatar {
                border-radius: 50%;
                vertical-align: middle;
                margin-right: 10px;
            }
            .status {
                font-size: 30px;
                margin: 2px 2px 0 0;
                display: inline-block;
                vertical-align: middle;
                line-height: 10px;
            }
            .text-success {
                color: #10c469;
            }
            .text-info {
                color: #62c9e8;
            }
            .text-warning {
                color: #FFC107;
            }
            .text-danger {
                color: #ff5b5b;
            }
            .pagination {
                float: right;
                margin: 0 0 5px;
            }
            .pagination li a {
                border: none;
                font-size: 13px;
                min-width: 30px;
                min-height: 30px;
                color: #999;
                margin: 0 2px;
                line-height: 30px;
                border-radius: 2px !important;
                text-align: center;
                padding: 0 6px;
            }
            .pagination li a:hover {
                color: #666;
            }
            .pagination li.active a, .pagination li.active a.page-link {
                background: #03A9F4;
            }
            .pagination li.active a:hover {
                background: #0397d6;
            }
            .pagination li.disabled i {
                color: #ccc;
            }
            .pagination li i {
                font-size: 16px;
                padding-top: 6px
            }
            .hint-text {
                float: left;
                margin-top: 10px;
                font-size: 13px;
            }
            .button:hover {background-color: #cccccc}
        </style>
        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
    </head>
    <body>
        <jsp:include page="Common/Header.jsp"></jsp:include>
            
            <div class="container-xl">
                <div style="height: 100px">
                    
                </div>
                <div class="table-responsive" style="margin:100px 0px;">
                    <nav aria-label="breadcrumb" class="main-breadcrumb" style="margin-bottom: 15px;font-size: large">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="home">Home</a></li>
                        <li class="breadcrumb-item"><a href="usercoursedetail?courseId=${sessionScope.course.courseId}">${sessionScope.course.courseName}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Quiz : ${sessionScope.quiz.title}</li>
                    </ol>
                    </nav>
                    <div class="row" style="display: flex;justify-content:center;align-items: center;flex-direction: column;margin-bottom: 50px">
                        <h4>Time Limit :${sessionScope.quiz.duration} minutes</h4>
                        <h4>Number of question: ${sessionScope.quiz.numberOfQuestion}</h4>
                    </div>
                        
                    <div class="table-wrapper">
                        <div class="table-title">
                            <div class="row">
                                <div class="col-sm-12">
                                    <h1>History of attempt</h1>
                                <h5></h5>
                                
                            </div>
                            

                        </div>
                    </div>

                    <h5 style="color: green;text-align: center">${requestScope.ms}</h5>
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                
                                <th>Attempt</th>
                                <th>Start</th>
                                <th>End</th>
                                <th>Time taken</th>
                                <th>True Question</th>
                                <th>Grade/10</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <c:forEach items="${requestScope.attemptList}" var="a" >
                                <tr>
                                    
                                    <td>${a.attempt}</td>
                                    <td><fmt:formatDate pattern = "yyyy-MM-dd HH:mm" value = "${a.start}" /></td>
                                    <td><fmt:formatDate pattern = "yyyy-MM-dd HH:mm" value = "${a.end}" /></td>
                                    <td>${a.time}</td>
                                    <td>${a.mark}</td> 
                                    <td>${a.grade}</td>
                                    <td><a href="historyreview?historyId=${a.id}">Review</a></td>


                                </tr>
                                
                            </c:forEach>


                        </tbody>
                    </table>
                    
                    
                </div>
                   <c:if test="${requestScope.high >0}"> <h3 style="margin: 20px 0px;float:left">Highest Score: ${requestScope.high}</h3>
                   
                   <c:if test="${requestScope.high >=7}"><h2 style="margin: 20px 0px;float:right;color: green">PASS</h2></c:if>
                   </c:if>
            </div>
                    
                   
                        <form action="quiz" style="display: flex;justify-content:center;align-items: center;flex-direction: column;margin-bottom: 50px;">
                            <input style="width: 175px;height: 45px;border-radius:5px;background-color: #999999" type="submit" value="Attempt Quiz" />
                        </form> 
                    
                    
        </div> 
                 
        <jsp:include page="Common/QuizSider.jsp"></jsp:include>
        <jsp:include page="Common/Footer.jsp"></jsp:include>
       
    </body>
     
    <script>

    </script>
</html>

Quiz_Learn/Quiz/web/SliderList.jsp
<%-- 
    Document   : Slider
    Created on : 21-09-2023, 08:36:40
    Author     : admin
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
 <!DOCTYPE html>
<!-- Coding By CodingNepal - www.codingnepalweb.com -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Slider</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="style.css">
    <style>
        /* Importing Google font - Open Sans */
@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&display=swap');

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Open Sans', sans-serif;
}

body {
    background: #ecececdb;
}

.card-list {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    max-width: 1250px;
    margin: 150px auto;
    padding: 20px;
    gap: 20px;
}

.card-list .card-item {
    background: #fff;
    padding: 26px;
    border-radius: 8px;
    box-shadow: 0px 5px 10px rgba(0, 0, 0, 0.04);
    list-style: none;
    cursor: pointer;
    text-decoration: none;
    border: 2px solid transparent;
    transition: border 0.5s ease;
}

.card-list .card-item:hover {
    border: 2px solid #000;
}

.card-list .card-item img {
    width: 100%;
    aspect-ratio: 16/9;
    border-radius: 8px;
    object-fit: cover;
}

.card-list span {
    display: inline-block;
    background: #F7DFF5;
    margin-top: 32px;
    padding: 8px 15px;
    font-size: 0.75rem;
    border-radius: 50px;
    font-weight: 600;
}

.card-list .developer {
    background-color: #F7DFF5; 
    color: #B22485;
}   

.card-list .designer {
    background-color: #d1e8ff;
    color: #2968a8;
}

.card-list .editor {
    background-color: #d6f8d6; 
    color: #205c20;
}

.card-item h3 {
    color: #000;
    font-size: 1.438rem;
    margin-top: 28px;
    font-weight: 600;
}

.card-item .arrow {
    display: flex;
    align-items: center;
    justify-content: center;
    transform: rotate(-35deg);
    height: 40px;
    width: 40px;
    color: #000;
    border: 1px solid #000;
    border-radius: 50%;
    margin-top: 40px;
    transition: 0.2s ease;
}

.card-list .card-item:hover .arrow  {
    background: #000;
    color: #fff; 
}

@media (max-width: 1200px) {
    .card-list .card-item {
        padding: 15px;
    }
}

@media screen and (max-width: 980px) {
    .card-list {
        margin: 0 auto;
    }
}
    </style>
</head>
<body>
     <jsp:include page="Common/Management.jsp"></jsp:include>
    <div class="card-list">
        <c:forEach items="${slider}" var="s">
            
        <a href="slider-details?id=${s.sliderId}" class="card-item">
            <img style="max-height: 200px; max-width: 200px" src="${s.image}" alt="Card Image">
            <span class="developer">${s.title}</span>
            <h3>${s.content}</h3>
            <div class="arrow">
                <i class="fas fa-arrow-right card-icon"></i>
            </div>
        </a>
        </c:forEach>
        
    </div>
    <jsp:include page="Common/Sidebar.jsp"></jsp:include>
    <jsp:include page="Common/Footer.jsp"></jsp:include>
</body>
</html>