Watch-Store/WatchProjectNew_final/src/java/model/Product.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import java.sql.Date;

/**
 *
 * @author khiem
 */
public class Product {
    private String id,name;
    private double price;
    private String describe,image;
    private Category category;
    private String details;
    private int sale;
    private Date date;
    private int Tid;
    private int rating;

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }
    
    public int getTid() {
        return Tid;
    }

    public void setTid(int Tid) {
        this.Tid = Tid;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
    public Product() {
    }

    public Product(String id, String name, double price, String describe, String image, Category category, String details) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.describe = describe;
        this.image = image;
        this.category = category;
        this.details = details;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getPrice() {
        return price;
    }

    public int getSale() {
        return sale;
    }

    public void setSale(int sale) {
        this.sale = sale;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public String getDescribe() {
        return describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

   
    
    

    
    
    
}

Watch-Store/WatchProjectNew_final/web/header-footer/footer.jsp
<%-- 
    Document   : footer
    Created on : Jun 19, 2023, 4:20:59 PM
    Author     : khiem
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %> 


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <title>Electro - HTML Ecommerce Template</title>

        <!-- Google font -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

        <!-- Bootstrap -->
        <link type="text/css" rel="stylesheet" href="css/bootstrap.min.css"/>

        <!-- Slick -->
        <link type="text/css" rel="stylesheet" href="css/slick.css"/>
        <link type="text/css" rel="stylesheet" href="css/slick-theme.css"/>

        <!-- nouislider -->
        <link type="text/css" rel="stylesheet" href="css/nouislider.min.css"/>

        <!-- Font Awesome Icon -->
        <link rel="stylesheet" href="css/font-awesome.min.css">

        <!-- Custom stlylesheet -->
        <link type="text/css" rel="stylesheet" href="css/home.css"/>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
    <body>
        <!-- FOOTER -->
        <footer id="footer">
            <!-- top footer -->
            <div class="section">
                <!-- container -->
                <div class="container">
                    <!-- row -->
                    <div class="row">
                        <div class="col-md-4 col-xs-6">
                            <div class="footer">
                                <h3 class="footer-title">About Us</h3>
                                <p>A watch store where you can find anything you want hope you enjoy your time here</p>
                                <ul class="footer-links">
                                    <li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
                                    <li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
                                    <li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
                                </ul>
                            </div>
                        </div>

                        <div class="col-md-4 col-xs-6">
                            <div class="footer">
                                <h3 class="footer-title">Categories</h3>
                                <ul class="footer-links">
                                    <li><a href="#">Rolex</a></li>
                                    <li><a href="#">Fossil</a></li>
                                    <li><a href="#">Casio</a></li>
                                    <li><a href="#">Tissot</a></li>
                                    <li><a href="#">Watch</a></li>
                                </ul>
                            </div>
                        </div>

                        <div class="clearfix visible-xs"></div>

                        <div class="col-md-4 col-xs-6">
                            <div class="footer">
                                <h3 class="footer-title">Information</h3>
                                <ul class="footer-links">
                                    <li><a href="#">About Us</a></li>
                                    <li><a href="#">Contact Us</a></li>
                                    <li><a href="#">Privacy Policy</a></li>
                                    <li><a href="#">Orders and Returns</a></li>
                                    <li><a href="#">Terms & Conditions</a></li>
                                </ul>
                            </div>
                        </div>

                        
                    </div>
                    <!-- /row -->
                </div>
                <!-- /container -->
            </div>
            <!-- /top footer -->

            <!-- bottom footer -->
            <div id="bottom-footer" class="section">
                <div class="container">
                    <!-- row -->
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <ul class="footer-payments">
                                <li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
                                <li><a href="#"><i class="fa fa-credit-card"></i></a></li>
                                <li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
                                <li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
                                <li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
                                <li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
                            </ul>
                            
                        </div>
                    </div>
                    <!-- /row -->
                </div>
                <!-- /container -->
            </div>
            <!-- /bottom footer -->
        </footer>
        <!-- /FOOTER -->
    <script src="js/jquery.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/slick.min.js"></script>
        <script src="js/nouislider.min.js"></script>
        <script src="js/jquery.zoom.min.js"></script>
        <script src="js/main.js"></script>
    </body>
</html>

Watch-Store/WatchProjectNew_final/web/header-footer/header.jsp
<%-- 
    Document   : header
    Created on : Jun 19, 2023, 3:02:58 PM
    Author     : khiem
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %> 


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <title>Electro - HTML Ecommerce Template</title>

        <!-- Google font -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

        <!-- Bootstrap -->
        <link type="text/css" rel="stylesheet" href="css/bootstrap.min.css"/>

        <!-- Slick -->
        <link type="text/css" rel="stylesheet" href="css/slick.css"/>
        <link type="text/css" rel="stylesheet" href="css/slick-theme.css"/>

        <!-- nouislider -->
        <link type="text/css" rel="stylesheet" href="css/nouislider.min.css"/>

        <!-- Font Awesome Icon -->
        <link rel="stylesheet" href="css/font-awesome.min.css">

        <!-- Custom stlylesheet -->
        <link type="text/css" rel="stylesheet" href="css/home.css"/>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style>
            .manage{
                color:white;
            }
            .product-img img{
                width: 20px;
                height: 20px;
            }
        </style>
    </head>
    <body>
        <!-- HEADER -->
        <header>
            <!-- TOP HEADER -->
            <div id="top-header">
                <div class="container">
                    <ul class="header-links pull-left">
                        <li><a href="#"><i class="fa fa-phone"></i> +021-95-51-84</a></li>
                        <li><a href="#"><i class="fa fa-envelope-o"></i> email@email.com</a></li>
                        <li><a href="#"><i class="fa fa-map-marker"></i> 1734 Stonecoal Road</a></li>
                    </ul>
                    <ul class="header-links pull-right">

                        <c:if test="${(sessionScope.account==null)}">
                            <%
                                String uri=request.getRequestURI();
                                String query=request.getQueryString();
                                String URL="";
                                if((uri.contains("home.jsp"))||uri==null){
                                    URL+="home";
                                }else if(uri.contains("cart.jsp")||uri.contains("profile.jsp")||uri.contains("TransactionInfo.jsp")||uri.contains("UserSpendingInfo.jsp")||uri.contains("TransactionAll")||uri.contains("accountInfo1.jsp")||uri.contains("accountView.jsp")){
                                        URL+="home";
                                    }
                                else if(!uri.contains("home.jsp") &&query==null){

                                URL+=uri.substring(uri.lastIndexOf("/")+1, uri.length());
                                }else{
                                    URL+=uri.substring(uri.lastIndexOf("/")+1, uri.length())+"?"+query;}
                                
                            %>

                            <li><a href="login?url=<%=URL.replaceAll("&", ";")%>">Login</a></li>
                            <li><a href="signup">Register</a></li>
                            </c:if>
                            <c:if test="${(sessionScope.account!=null)}">
                                <%
                                    String uri=request.getRequestURI();
                                    String query=request.getQueryString();
                                    String URL="";
                                    if((uri.contains("home.jsp")) &&uri==null){
                                        URL+="home";
                                    }
                                    else if(uri.contains("cart.jsp")||uri.contains("profile.jsp")||uri.contains("TransactionInfo.jsp")||uri.contains("UserSpendingInfo.jsp")||uri.contains("TransactionAll")||uri.contains("accountInfo1.jsp")||uri.contains("accountView.jsp")){
                                        URL+="home";
                                    }
                                    
                                    else if(!uri.contains("home.jsp") &&query==null){

                                    URL+=uri.substring(uri.lastIndexOf("/")+1, uri.length());
                                    }else{
                                        URL+=uri.substring(uri.lastIndexOf("/")+1, uri.length())+"?"+query;}
                                
                                %>
                            <h4 style="font-size: x-small"></h4>
                            <li><a href="logout?url=<%=URL.replaceAll("&", ";")%>">Logout</a></li>
                            <li><a target="_blank" href="profile"><c:if test="${sessionScope.accountimage eq null}"><img src="img/face.png" width="20" height="20" style="border-radius: 100px;"></c:if><c:if test="${sessionScope.accountimage ne null}"><img src="data:image/jpg;base64,${sessionScope.accountimage}" data-index="0" width="20" height="20" style="border-radius: 100px;"> </c:if>My Account</a></li>
                            </c:if>

                    </ul>
                </div>
            </div>
            <!-- /TOP HEADER -->

            <!-- MAIN HEADER -->
            <div id="header">
                <!-- container -->
                <div class="container">
                    <!-- row -->
                    <div class="row">
                        <!-- LOGO -->
                        <div class="col-md-3">
                            <div class="header-logo">
                                <a href="home" class="logo">
                                    <img src="./img/logo.png" alt="">
                                </a>
                            </div>
                        </div>
                        <!-- /LOGO -->

                        <!-- SEARCH BAR -->
                        <div class="col-md-6">
                            <div class="header-search">
                                <form action="search">
                                    <input type="hidden" name="cid" value="0">
                                    <input class="input" placeholder="Search here" name="search">
                                    <input type="hidden" name="page" value="1">
                                    <button class="search-btn" >Search</button>
                                </form>
                            </div>
                        </div>
                        <!-- /SEARCH BAR -->

                         <!-- ACCOUNT -->
                        <div class="col-md-3 clearfix">
                            <div class="header-ctn">
                                <c:if test="${sessionScope.account.role eq 2}">
                                    <a href="crud" class="manage">
                                        <i class="fa fa-shopping-bag"></i>
                                        <span>Mangager</span>
                                    </a>
                                </c:if>
                                <!-- Wishlist -->
                                

                                    <!-- Cart -->
                                    
                                       <!-- /Wishlist -->
                                    <div>
                                        <a href="cartUpload?aid=${sessionScope.account.aid}">
                                            <i class="fa fa-shopping-cart"></i>
                                            <span>Cart</span>
                                            <div class="qty">${fn:length(sessionScope.cartList)}</div>
                                        </a>
                                    </div>
                                  
                                    <!-- /Cart -->
                              
                                <!-- Menu Toogle -->
                                <div class="menu-toggle">
                                    <a href="#">
                                        <i class="fa fa-bars"></i>
                                        <span>Menu</span>
                                    </a>
                                </div>
                                <!-- /Menu Toogle -->
                            </div>
                        </div>
                        <!-- /ACCOUNT -->
                    </div>
                    <!-- row -->
                </div>
                <!-- container -->
            </div>
            <!-- /MAIN HEADER -->
        </header>
        <!-- /HEADER -->
        <!-- jQuery Plugins -->
        <script src="js/jquery.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/slick.min.js"></script>
        <script src="js/nouislider.min.js"></script>
        <script src="js/jquery.zoom.min.js"></script>
        <script src="js/main.js"></script>
    </body>
</html>

Watch-Store/WatchProjectNew_final/web/header-footer/manager.jsp
<%-- 
    Document   : header
    Created on : Jun 19, 2023, 3:02:58 PM
    Author     : khiem
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %> 


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <title>Electro - HTML Ecommerce Template</title>

        <!-- Google font -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

        <!-- Bootstrap -->
        <link type="text/css" rel="stylesheet" href="css/bootstrap.min.css"/>

        <!-- Slick -->
        <link type="text/css" rel="stylesheet" href="css/slick.css"/>
        <link type="text/css" rel="stylesheet" href="css/slick-theme.css"/>

        <!-- nouislider -->
        <link type="text/css" rel="stylesheet" href="css/nouislider.min.css"/>

        <!-- Font Awesome Icon -->
        <link rel="stylesheet" href="css/font-awesome.min.css">

        <!-- Custom stlylesheet -->
        <link type="text/css" rel="stylesheet" href="css/home.css"/>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style>
            .navbar-nav{
                flex-direction: row;
            }
        </style>
    </head>
    <body>
        <!-- NAVIGATION -->
        <nav id="navigation">
            <!-- container -->
            <div class="container">
                <!-- responsive-nav -->
                <div id="responsive-nav">
                    <!-- NAV -->
                    <ul class="main-nav nav navbar-nav">
                        <c:if test="${param.aid eq null}">
                            <li><a href="home">Home</a></li>
                            <li <%if(request.getRequestURI().contains("crud.jsp")){%> class="active" <%}%> ><a href="crud">Manage Product</a></li>
                            <li <%if(request.getRequestURI().contains("crudcategory.jsp")){%> class="active" <%}%> ><a href="crudcategory">Manage Brand</a></li>
                            <li <%if(request.getRequestURI().contains("accountView.jsp")){%> class="active" <%}%> ><a href="accountmanagement">Manage Account</a></li>
                            <li <%if(request.getRequestURI().contains("TransactionAll.jsp")){%> class="active" <%}%> ><a href="transaction">Manage Transaction</a></li>
                            <li <%if(request.getRequestURI().contains("SaleChart.jsp")){%> class="active" <%}%> ><a href="chart">Statistics Sale Growth</a></li>
                            <li <%if(request.getRequestURI().contains("UserChart.jsp")){%> class="active" <%}%> ><a href="userchart">Statistics Customer</a></li>
                            </c:if>
                        
                            <c:if test="${param.aid ne null}">
                            <li ${param.cid ne null ?'class="active"':''}><a href="accountmanagement">Manage Account</a></li>
                            <li ${param.cid ne null ?'class="active"':''}><a href="crud">Account profile</a></li>
                            </c:if>
                           

                    </ul>
                    <!-- /NAV -->
                </div>
                <!-- /responsive-nav -->
            </div>
            <!-- /container -->
        </nav>
        <!-- /NAVIGATION -->
        <!-- jQuery Plugins -->
        <script src="js/jquery.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/slick.min.js"></script>
        <script src="js/nouislider.min.js"></script>
        <script src="js/jquery.zoom.min.js"></script>
        <script src="js/main.js"></script>
    </body>
</html>

Watch-Store/WatchProjectNew_final/web/header-footer/transact.jsp
<%-- 
    Document   : header
    Created on : Jun 19, 2023, 3:02:58 PM
    Author     : khiem
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %> 


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <title>Electro - HTML Ecommerce Template</title>

        <!-- Google font -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

        <!-- Bootstrap -->
        <link type="text/css" rel="stylesheet" href="css/bootstrap.min.css"/>

        <!-- Slick -->
        <link type="text/css" rel="stylesheet" href="css/slick.css"/>
        <link type="text/css" rel="stylesheet" href="css/slick-theme.css"/>

        <!-- nouislider -->
        <link type="text/css" rel="stylesheet" href="css/nouislider.min.css"/>

        <!-- Font Awesome Icon -->
        <link rel="stylesheet" href="css/font-awesome.min.css">

        <!-- Custom stlylesheet -->
        <link type="text/css" rel="stylesheet" href="css/home.css"/>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style>
            .navbar-nav{
                flex-direction: row;
            }
        </style>
    </head>
    <body>
        <!-- NAVIGATION -->
        <nav id="navigation">
            <!-- container -->
            <div class="container">
                <!-- responsive-nav -->
                <div id="responsive-nav">
                    <!-- NAV -->
                    <ul class="main-nav nav navbar-nav">
                        <c:if test="${param.tid ne null}">
                            <li <%if(request.getRequestURI().contains("TransactionAll.jsp")){%> class="active" <%}%> ><a href="transaction">Manage Transaction</a></li>
                            <li <%if(request.getRequestURI().contains("TransactionInfo.jsp")){%> class="active" <%}%> ><a href="transactioninfo?tid=${param.tid}">Transaction Info</a></li>

                        </c:if>
                        <c:if test="${param.aid ne null}">
                            <li <%if(request.getRequestURI().contains("AccountView.jsp")){%> class="active" <%}%> ><a href="accountmanagement">Manage Account</a></li>
                            <li <%if(request.getRequestURI().contains("UserSpendingInfo.jsp")){%> class="active" <%}%> ><a href="userspending?aid=${param.aid}">Manage User Purchase</a></li>

                        </c:if>
                        
                                                   

             
                        
                           

                    </ul>
                    <!-- /NAV -->
                </div>
                <!-- /responsive-nav -->
            </div>
            <!-- /container -->
        </nav>
        <!-- /NAVIGATION -->
        <!-- jQuery Plugins -->
        <script src="js/jquery.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/slick.min.js"></script>
        <script src="js/nouislider.min.js"></script>
        <script src="js/jquery.zoom.min.js"></script>
        <script src="js/main.js"></script>
    </body>
</html>